name: Client & Server CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  client_checks:
    name: Client Checks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Lint Client
      run: npm run lint --workspace=client
    - name: Build Client
      run: npm run build --workspace=client

  test:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Images
      run: docker compose build server

    - name: Start Infrastructure (DB & Redis)
      run: |
        docker compose up -d postgres redis
        echo "⏳ Waiting for Database..."
        until docker compose exec -T postgres pg_isready -U user; do
          echo "Waiting for postgres..."
          sleep 2
        done
        echo "✅ Database Ready!"

    - name: Run Integration Tests
      # Use built image dependencies directly
      run: |
        docker compose run --rm server sh -c "cd server && npx prisma db push && npm run test"

  deploy:
    name: Deploy to AWS
    needs: [test, client_checks]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Deploy Infrastructure
      run: |
        # Installation dependnecies for script
        sudo apt-get install -y jq
        
        # Run deployment script non-interactively
        # Note: You must set AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY secrets in GitHub Repo Settings
        ./deploy_infra.sh
